---
driver:
  name: digitalocean

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-14.04
    driver_config:
      region: ams2
      size: 2gb

suites:
  - name: default
    # test the role
    run_list:
      - role[base]
    # test an individual recipe... or recipe combos
    # run_list:
    #   - recipe[apt]
    #   - recipe[build-essential]
    #   - recipe[python]
    #   - recipe[cron]
    #   - recipe[yolo::default]
    # attributes:
    #   java:
    #     install_flavor: "oracle",
    #     jdk_version: "7"
